parameters:
    socloz.nsq.delayed.topic_name: __socloz_delayed

services:
    socloz.nsq.registry:
        class: Socloz\NsqBundle\TopicRegistry
        arguments:
            - @service_container

    socloz.nsq.subscriber.message_exception:
        class: Socloz\NsqBundle\Event\MessageExceptionSubscriber
        tags:
            - { name: socloz.nsq.event_subscriber }

    socloz.nsq.logger:
        class: Socloz\NsqBundle\Logger\MonologAdapter
        arguments: ["@logger"]
#  socloz.nsq.delayed_messages.consumer:
#    class: Socloz\NsqBundle\Delayed\Consumer
#    lazy: true
#    arguments: ["@socloz.nsq"]
#    tags:
#    -  { name: socloz.nsq.consumer, topic: %socloz.nsq.delayed.topic_name%, channel: default }
